name: serviapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.0
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0
  firebase_storage: ^12.2.0
  image_picker: ^1.0.4
  uuid: ^4.5.1
  fl_chart: ^0.65.0
  pay: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/