// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa_mnbc1GKGN9CQfNiLcwFtBvB0a_csHI',
    appId: '1:654764768624:web:e0ea76a9388aa8d64ba3b5',
    messagingSenderId: '654764768624',
    projectId: 'serviapp-87a43',
    authDomain: 'serviapp-87a43.firebaseapp.com',
    storageBucket: 'serviapp-87a43.firebasestorage.app',
    measurementId: 'G-92F53DCMZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmnymf-uJ19zO0KTI1ebdV5oequ5yAT8',
    appId: '1:654764768624:android:38fa17f982a692d44ba3b5',
    messagingSenderId: '654764768624',
    projectId: 'serviapp-87a43',
    storageBucket: 'serviapp-87a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCef7gAQDuuQ_MpYiHLjq_kb3Nkndxsx_k',
    appId: '1:654764768624:ios:33d491e49d3d37804ba3b5',
    messagingSenderId: '654764768624',
    projectId: 'serviapp-87a43',
    storageBucket: 'serviapp-87a43.firebasestorage.app',
    iosBundleId: 'com.example.serviapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCef7gAQDuuQ_MpYiHLjq_kb3Nkndxsx_k',
    appId: '1:654764768624:ios:33d491e49d3d37804ba3b5',
    messagingSenderId: '654764768624',
    projectId: 'serviapp-87a43',
    storageBucket: 'serviapp-87a43.firebasestorage.app',
    iosBundleId: 'com.example.serviapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa_mnbc1GKGN9CQfNiLcwFtBvB0a_csHI',
    appId: '1:654764768624:web:f3765960b194c0794ba3b5',
    messagingSenderId: '654764768624',
    projectId: 'serviapp-87a43',
    authDomain: 'serviapp-87a43.firebaseapp.com',
    storageBucket: 'serviapp-87a43.firebasestorage.app',
    measurementId: 'G-ECL7555Z49',
  );
}
